targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        dev_options:
          compilers:
            dartdevc:
        release_options:
          compilers:
            dart2js:
              args: ["-O4"]
            dart2wasm:
              args: ["-O3"]
